[tool.poetry]
name = "icli"
version = "0.8.4"
description = "ibkr cli et al"
authors = ["Matt Stancliff <matt@genges.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

# IB API wrapper with better usability than the IBKR-provided libs
ib_async = ">=1.0.2"
# ib_async = { path = "../../ibkr/ib_insync", develop = true }

# nice printing and data manipulation
pandas = ">2.1.0"

# easy time access
pendulum = {version = "^3.0.0b1", allow-prereleases = true}

# running / logging
prompt-toolkit = "^3.0.29"
loguru = ">0.6.0"

# for multi-step cli prompts
questionary = "^1.9.0"
tableprint = "^0.9.1"

# for ANSI console color gradients
seaborn = "^0.12.2"

# for showing nice things
prettyprinter = "^0.18.0"
setproctitle = "^1.2.2"

# saving things and converting IBKR HTML news into readable text
diskcache = "^5.2.1"
beautifulsoup4 = "^4.9.3"

# our API helpers and wrappers
tradeapis = { git = "https://github.com/mattsta/tradeapis.git", tag="2.4.2" }
schedule = "^1.1.0"
httpx = "^0.25.2"
requests = "^2.32.4"
discord = "^2.3.2"
selfcord = "^0.2.5"

[tool.poetry.scripts]
icli = "icli.__main__:runit"

[tool.poetry.group.dev.dependencies]
mypy = "^1.4.1"
data-science-types = "^0.2.23"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
